databases:
  - name: chanmio_DB
    databaseName: chanmio_db
    user: chanmio
    region: singapore

services:
  - type: web
    name: chanmio
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chanmio_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

